#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a add_header $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx start
