#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -lt 11 ]
do
	if [ $i == 4 ]
	then
		echo "Bad Luck"
	elif [ $i == 8 ]
	then
		echo "Good Luck"
	else
		echo "Holberton School"
	fi

	((i++))
done
