#!/usr/bin/env bash
# checks a file
FILE=holbertonschool
if [ -e "$FILE" ]; then
	echo "holbertonschool file exists"

	# checks if file contains something
	if [ -s "$FILE" ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi

	# checks if the file is a regular file
	if [ -f "$FILE" ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi

